FROM mcr.microsoft.com/playwright:v1.61.1-jammy
WORKDIR /app

COPY package.json /app/package.json
RUN npm install --omit=dev

COPY runner.js /app/runner.js
COPY alpsTradeExport.js /app/alpsTradeExport.js
COPY ALPS_closed_ledger_authority_v10147.js /app/ALPS_closed_ledger_authority_v10147.js
COPY src /app/src
COPY public /app/public
COPY legacy /app/legacy
COPY recovery /app/recovery

ENV HOST=0.0.0.0
ENV PORT=8787
ENV ALPS_AUTO_START_WATCH=1
ENV ALPS_AUTO_START_LAB=1
ENV ALPS_HEADLESS=1
ENV ALPS_TICK_MS=60000
ENV ALPS_REPORT_EVERY_MS=60000
ENV ALPS_FORWARD_STALE_MS=5400000
ENV ALPS_AUTO_RELOAD_STALE_FORWARD=1
ENV ALPS_V102_SUPERVISOR_POLL_MS=10000
ENV ALPS_V102_FAST_HARD_DEADLINE_MS=18000
ENV ALPS_V102_FAST_STALL_SEC=45
ENV ALPS_V102_FAST_FAILURE_RESTART_THRESHOLD=3
ENV ALPS_V102_ADAPTER_RESTART_COOLDOWN_SEC=120
ENV ALPS_V102_HEAVY_CIRCUIT_COOLDOWN_SEC=600
ENV ALPS_V102_LEGACY_HEAVY_AUDIT=0
ENV ALPS_V102_CANDIDATE_GAP_CONFIRM_OBSERVATIONS=4
ENV ALPS_V102_CANDIDATE_GAP_CONFIRM_SEC=20
ENV ALPS_DATA_DIR=/data/alps
ENV ALPS_REPORT_DIR=/data/alps/reports
ENV ALPS_PROFILE_DIR=/data/alps/chromium-profile

EXPOSE 8787
CMD ["npm", "start"]
